import pyautogui
x = pyautogui
x.click(665,765)
x.click(654,688,duration=10)
x.keyUp('win')
x.press('up')
x.keyDown('win')
x.hotkey('win','left')
x.hotkey('win','down')
x.click(13,406,duration=10)
x.click(90,424,duration=10)
x.hotkey('win','left')
x.hotkey('win','up')
x.click(22,405)
x.moveTo(7,420)
x.click(24,422)
x.typewrite('python Note.txt',interval=2)
x.MoveTo(197,363,duration=5)
x,y = x.locateCentreOnScreen('c:\\Users\Angular_nija_avenger\desktop\index.png')
x.click(x,y)
x.hotkey('win','right')
x.hotkey('win','up')